# Generated by Django 5.2 on 2025-05-15 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cle_securite',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
