app = "jeuxolympiquesparis2024"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[processes]
  app = "gunicorn olympic_tickets.wsgi:application --bind 0.0.0.0:8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.checks]]
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/"
