# Generated by Django 5.2 on 2025-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(choices=[(1, 'Solo'), (2, 'Duo'), (4, 'Famille')])),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
