# Generated by Django 5.2 on 2025-05-29 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_reservation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cle_finale', models.CharField(blank=True, max_length=255)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.offre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
