# Generated by Django 5.2 on 2025-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cle_finale',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
